---TASK 3---

--14. Find the total number of couriers handled by each employee
      select * from Employee
	  select * from Courier

	  select  e.EmployeeId, Name, count(CourierId) as TotalCouriers from Employee e join Courier c on e.EmployeeID = c.EmployeeId group by e.EmployeeId, Name

	  select EmployeeId,  count (CourierId) as TotalCouriers from Courier Group by EmployeeId


--15. Calculate the total revenue generated by each location
      select * from Payment
	  select * from Location

	  Select LocationID,sum(amount) AS TotalRevenue from Payment Group by LocationID

	  select p.LocationID, LocationName, sum(Amount) as TotalRevenue from Payment p join Location l on p.LocationID = l.LocationID group by p.LocationID, LocationName
	  


--16. Find the total number of couriers delivered to each location.
      select * from Location
	  select * from Courier

	  
	  select LocationID,count(CourierID) AS CourierDelivered from Payment group by LocationID

--17. Find the courier with the highest average delivery time
      select CourierId, datediff(Day,PaymentDate, DeliveryDate) as AvgDT from Courier order by AvgDT desc
      

--18. Find Locations with Total Payments Less Than a Certain Amount 
      select * from Payment
	  select LocationId, CourierId, Amount from Payment where Amount <500 order by Amount

--19. Calculate Total Payments per Location 
      select * from Payment
	  select LocationId , count (PaymentId) as TotalPayments from Payment group by LocationId  order by LocationID

--20. Retrieve couriers who have received payments totaling more than $1000 in a specific location (LocationID = X): 
      select * from Payment
	  select CourierId, sum(Amount) as Amount from Payment where  LocationID = 1 group by CourierID Having sum(Amount)>500

	


--**21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD'): 
        select CourierId from Payment where PaymentDate >'2023-09-25' and Amount >1000 group by CourierID
      
	    select * from Payment

	
--**22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD') 
        select LocationId from Payment where PaymentDate >'2023-09-25' and Amount >200 group by LocationID